trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  # Define variables for SonarQube
  SONARQUBE_PROJECT_KEY: 'your-project-key'  # Set this as needed
  SONARQUBE_URL: 'https://sonar-dev.supervity.ai'
  SONARQUBE_TOKEN: '-sqa_621f69d3290cb9967ec7da221c1edfd093d75c24'

steps:

# 1. Use the desired Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

# 2. Install Python dependencies and build the project
- script: |
    echo "Installing Python dependencies..."
    python -m pip install --upgrade pip
    python -m pip install -r requirements.txt
    python setup.py build
  displayName: 'Install Dependencies and Build Project'
  workingDirectory: 'path/to/your/project'  # Update this if necessary

# 3. Prepare SonarQube for analysis
- task: SonarQubePrepare@6
  inputs:
    SonarQube: 'SonarQube'  # This should match the name of the SonarQube service connection in Azure DevOps
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: $(SONARQUBE_PROJECT_KEY)
    cliSources: '.'
    extraProperties: |
      sonar.host.url=$(SONARQUBE_URL)
      sonar.login=$(SONARQUBE_TOKEN)
  displayName: 'Prepare SonarQube Analysis'

# 4. Run SonarQube analysis
- task: SonarQubeAnalyze@6
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'
  displayName: 'Run SonarQube Analysis'

# 5. Publish SonarQube results
- task: SonarQubePublish@6
  inputs:
    pollingTimeoutSec: '300'
  displayName: 'Publish SonarQube Quality Gate Result'
