trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_PROJECT_KEY: 'Infra-Test_Infra-Test_925dc69a-6aa8-40cd-8ff4-4b5b537f42f9'
  SONARQUBE_PROJECT_NAME: 'python-mini-project'
  SONARQUBE_PROJECT_VERSION: '1.0'
  SONARQUBE_SERVICE_CONNECTION: 'sonarqube'  # Name of the SonarQube service connection in Azure DevOps
  BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)

stages:
- stage: SonarQubeAnalysis
  displayName: 'SonarQube Analysis'
  jobs:
  - job: Analyze
    displayName: 'Analyze'
    steps:
    # Step 1: Checkout code from the repository
    - checkout: self
      persistCredentials: true

    # Step 2: Prepare SonarQube analysis
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: $(SONARQUBE_SERVICE_CONNECTION)
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: $(SONARQUBE_PROJECT_KEY)
        cliSources: $(BUILD_SOURCESDIRECTORY)
        extraProperties: |
          sonar.projectName=$(SONARQUBE_PROJECT_NAME)
          sonar.projectVersion=$(SONARQUBE_PROJECT_VERSION)
          sonar.host.url=$(SONARQUBE_URL)  # URL of your SonarQube server
          sonar.login=$(SONARQUBE_TOKEN)   # SonarQube authentication token

    # Step 3: Run SonarQube analysis
    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'

    # Step 4: Publish SonarQube Quality Gate results
    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'
