trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  SONARQUBE_PROJECT_KEY: 'Infra-Test_Infra-Test_925dc69a-6aa8-40cd-8ff4-4b5b537f42f9'
  SONARQUBE_PROJECT_NAME: 'python-mini-project'
  SONARQUBE_PROJECT_VERSION: '1.0'
  SONARQUBE_SERVICE_CONNECTION: 'sonarqube'  # Name of the SonarQube service connection in Azure DevOps
  BUILD_SOURCESDIRECTORY: $(Build.SourcesDirectory)

stages:
- stage: 'SonarQubeAnalysis'
  displayName: 'SonarQube Analysis'
  jobs:
  - job: 'Analyze'
    displayName: 'Analyze'
    steps:
    
    # Step 1: Checkout code from GitHub
    - checkout: self
      persistCredentials: true
    
    # Step 2: Set up Python environment (or adapt to your project's language)
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.x'
        addToPath: true

    # Step 3: Install dependencies and build the project
    - script: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python setup.py build
      displayName: 'Install Dependencies and Build Project'
    
    # Step 4: Prepare SonarQube analysis
    - task: SonarQubePrepare@6
      inputs:
        SonarQube: $(SONARQUBE_SERVICE_CONNECTION)  # Use the service connection name
        scannerMode: 'CLI'
        configMode: 'manual'
        cliProjectKey: $(SONARQUBE_PROJECT_KEY)
        cliSources: $(BUILD_SOURCESDIRECTORY)
        extraProperties: |
          sonar.projectName=$(SONARQUBE_PROJECT_NAME)
          sonar.projectVersion=$(SONARQUBE_PROJECT_VERSION)
          sonar.host.url=$(SONARQUBE_URL)  # Replace with the URL of your SonarQube server
          sonar.login=$(SONARQUBE_TOKEN)   # Replace with your SonarQube authentication token
    
    # Step 5: Run SonarQube analysis
    - task: SonarQubeAnalyze@6
      inputs:
        jdkversion: 'JAVA_HOME_17_X64'  # Java version compatible with SonarQube
    
    # Step 6: Publish SonarQube Quality Gate results
    - task: SonarQubePublish@6
      inputs:
        pollingTimeoutSec: '300'  # Time to wait for the SonarQube quality gate to complete

